### PR TITLE
Amd Support

### PR DESCRIPTION
**Pull request by robbmcleod**

### CODE REVIEW

**Comment by robbmcleod** [comment]
@drfinkus Do you want to pull these proposed changes and check them on OSX if you have access to that?

**Comment by drfinkus** [comment]
Sure, I can test on OSX in the coming days!

**Comment by drfinkus** [comment]
Confirmed working on Ubuntu 20.04 with AMD Threadripper 1920x. Testing on OSX next.

**Comment by drfinkus** [comment]
I will not be able to get access to an OSX for testing unfortunately. Can confirm working on Ubuntu as mentioned above.

**Comment by robbmcleod** [comment]
Ok I'll accept it and try and setup CI with Travis.

**Pull request merged**
